### PR TITLE
refactor: drop local asset support

### PR DESCRIPTION
**Pull request by duguyihou**

### CODE REVIEW

**Comment by ng-ha** [comment]
@duguyihou oh no, why did you drop local asset support?

**Comment by duguyihou** [comment]
@ng-ha 

To support local asset, we need consider different types of images(svg, gif, apng...) as well. Besides, RN image works well with local asset and supports different uris. `data:`, `res:`. I don't have capacity to do that, especially for Android. Then I realised that I should keep it in a small scope and not try to replace RN image. Maybe we can put it back in the future.

**Comment by duguyihou** [comment]
@ng-ha 

are you using `TurboImage` with local asset?

**Comment by ng-ha** [comment]
@duguyihou yes, i am. RN Image doesn't support some special formats of images

**Comment by duguyihou** [comment]
@ng-ha 

Can you tell me which formats are you using? Last week, I encountered some issues with local assets in Android release mode.
- app crash with svg
- apng does not play.

**Comment by ng-ha** [comment]
I tried local apng in debug mode, it worked fine. I haven't tried in release mode yet

**Comment by duguyihou** [comment]
sorry for the inconvenience.

**Pull request merged**
